### ISSUE TITLE
Repositories owned by different users are ignored?

### ISSUE THREAD

**Issue by himdel** [yasintoy/Alize#5]
Seems like this only reads repositories under $username, possibly only non-forked repositories.

This is definitely happening for Recent Commits, and Top Used Words. Not quite sure about rankings.

So, instead of a shiny profile, all I get is commits from my dotfiles :).

**Comment by yasintoy** [comment]
@himdel Forks are ignored. For all repository we have to call github api so i collect last 50 repository. If you want to customise it, you can install alize to in your computer and change whatever you want. Tell me if you’ll have any issue or question when you need

**Comment by himdel** [comment]
Thanks! :) I'll give that a try..
